theme: jekyll-theme-cayman
title: [Welcome to my Data Science Portfolio]
description: [Hi! I am Zinnia. This is where I have uploaded some of interesting Data Science and Machine Learning Projects I have worked on. If you like my work you can leave a comment or contact me in my Linkedin profile.]
"colors": {
      "text": "#333",
      "background": "#fff",
      "primary": "#666",
      "secondary": "#888",
      "highlight": "#1f80ff",
      "muted": "#f6f6f6",
      "border": "#eee"
    }
