theme: jekyll-theme-cayman
title: [Welcome to my Data Science Portfolio]
description: [Hi! I am Zinnia. Here I have uploaded some of interesting Data Science and Machine Learning Projects I have worked on.]
buttons:
      zip_url: https://www.linkedin.com/in/zinnia-mondal-659035b3/
      zip_title: LinkedIn
