theme: jekyll-theme-cayman
title: [Welcome to my Data Science Portfolio]
description: [Hi! I am Zinnia studying Masters at Politecnico di Torino Italy. This is my Github portfolio where I upload the diverse Data Science and Machine Learning Projects I have worked on. If you like my work you can leave a comment or contact me in my Linkedin profile.]
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"

