theme: jekyll-theme-cayman
title: [Welcome to my Data Science Portfolio]
description: [Hi! I am Zinnia, a MS student at Politecnico di Torino, Italy. This is my Github portfolio where I upload the diverse Data Science and Machine Learning Projects I have worked on.]
